global:
  scrape_interval: 15s

scrape_configs:
  - job_name: "node-exporter"
    static_configs:
      - targets: ["node_exporter:9100"]
# global"
#   scrape_interval:15s

# scrape_configs:
#   -jo_name:node-exporter
#     static_configs:
#       -targets: [node_exporter:9100]
